AIRPORT_METADATA = {
    # =========================
    # MÉXICO (MX)
    # =========================
    "MEX": {"city": "Ciudad de México", "region": "Ciudad de México", "country": "México"},
    "NLU": {"city": "Zumpango", "region": "Estado de México", "country": "México"},
    "TLC": {"city": "Toluca", "region": "Estado de México", "country": "México"},
    "GDL": {"city": "Guadalajara", "region": "Jalisco", "country": "México"},
    "MTY": {"city": "Monterrey", "region": "Nuevo León", "country": "México"},
    "CUN": {"city": "Cancún", "region": "Quintana Roo", "country": "México"},
    "TIJ": {"city": "Tijuana", "region": "Baja California", "country": "México"},
    "PVR": {"city": "Puerto Vallarta", "region": "Jalisco", "country": "México"},
    "SJD": {"city": "San José del Cabo", "region": "Baja California Sur", "country": "México"},
    "MZT": {"city": "Mazatlán", "region": "Sinaloa", "country": "México"},
    "HMO": {"city": "Hermosillo", "region": "Sonora", "country": "México"},
    "CUU": {"city": "Chihuahua", "region": "Chihuahua", "country": "México"},
    "CJS": {"city": "Ciudad Juárez", "region": "Chihuahua", "country": "México"},
    "MID": {"city": "Mérida", "region": "Yucatán", "country": "México"},
    "VER": {"city": "Veracruz", "region": "Veracruz", "country": "México"},
    "VSA": {"city": "Villahermosa", "region": "Tabasco", "country": "México"},
    "OAX": {"city": "Oaxaca", "region": "Oaxaca", "country": "México"},
    "HUX": {"city": "Huatulco", "region": "Oaxaca", "country": "México"},
    "PXM": {"city": "Puerto Escondido", "region": "Oaxaca", "country": "México"},
    "TGZ": {"city": "Tuxtla Gutiérrez", "region": "Chiapas", "country": "México"},
    "TAP": {"city": "Tapachula", "region": "Chiapas", "country": "México"},
    "AGU": {"city": "Aguascalientes", "region": "Aguascalientes", "country": "México"},
    "BJX": {"city": "León", "region": "Guanajuato", "country": "México"},
    "QRO": {"city": "Querétaro", "region": "Querétaro", "country": "México"},
    "SLP": {"city": "San Luis Potosí", "region": "San Luis Potosí", "country": "México"},
    "ZCL": {"city": "Zacatecas", "region": "Zacatecas", "country": "México"},
    "DGO": {"city": "Durango", "region": "Durango", "country": "México"},
    "TRC": {"city": "Torreón", "region": "Coahuila", "country": "México"},
    "CEN": {"city": "Ciudad Obregón", "region": "Sonora", "country": "México"},
    "LMM": {"city": "Los Mochis", "region": "Sinaloa", "country": "México"},
    "CUL": {"city": "Culiacán", "region": "Sinaloa", "country": "México"},
    "REX": {"city": "Reynosa", "region": "Tamaulipas", "country": "México"},
    "NLD": {"city": "Nuevo Laredo", "region": "Tamaulipas", "country": "México"},
    "TAM": {"city": "Tampico", "region": "Tamaulipas", "country": "México"},
    "MAM": {"city": "Matamoros", "region": "Tamaulipas", "country": "México"},
    "CLQ": {"city": "Colima", "region": "Colima", "country": "México"},
    "ZLO": {"city": "Manzanillo", "region": "Colima", "country": "México"},
    "UPN": {"city": "Uruapan", "region": "Michoacán", "country": "México"},
    "MLM": {"city": "Morelia", "region": "Michoacán", "country": "México"},
    "ACA": {"city": "Acapulco", "region": "Guerrero", "country": "México"},
    "ZIH": {"city": "Ixtapa-Zihuatanejo", "region": "Guerrero", "country": "México"},
    "PBC": {"city": "Puebla", "region": "Puebla", "country": "México"},
    "PAZ": {"city": "Poza Rica", "region": "Veracruz", "country": "México"},
    "XAL": {"city": "Xalapa", "region": "Veracruz", "country": "México"},
    "CTM": {"city": "Chetumal", "region": "Quintana Roo", "country": "México"},
    "CZM": {"city": "Cozumel", "region": "Quintana Roo", "country": "México"},
    "CPE": {"city": "Campeche", "region": "Campeche", "country": "México"},
    "TPQ": {"city": "Tepic", "region": "Nayarit", "country": "México"},
    "LOV": {"city": "Monclova", "region": "Coahuila", "country": "México"},
    "PDS": {"city": "Piedras Negras", "region": "Coahuila", "country": "México"},
    "SZT": {"city": "San Cristóbal de las Casas", "region": "Chiapas", "country": "México"},
    "AZP": {"city": "Atizapán de Zaragoza", "region": "Estado de México", "country": "México"},
    "CSL": {"city": "Cabo San Lucas", "region": "Baja California Sur", "country": "México"},
    "CNA": {"city": "Cananea", "region": "Sonora", "country": "México"},
    "BHL": {"city": "Bahía de los Ángeles", "region": "Baja California", "country": "México"},

    # =========================
    # ESTADOS UNIDOS (US)
    # =========================
    "ATL": {"city": "Atlanta", "region": "Georgia", "country": "Estados Unidos"},
    "LAX": {"city": "Los Angeles", "region": "California", "country": "Estados Unidos"},
    "ORD": {"city": "Chicago", "region": "Illinois", "country": "Estados Unidos"},
    "DFW": {"city": "Dallas-Fort Worth", "region": "Texas", "country": "Estados Unidos"},
    "DEN": {"city": "Denver", "region": "Colorado", "country": "Estados Unidos"},
    "JFK": {"city": "New York", "region": "New York", "country": "Estados Unidos"},
    "EWR": {"city": "Newark", "region": "New Jersey", "country": "Estados Unidos"},
    "LGA": {"city": "New York", "region": "New York", "country": "Estados Unidos"},
    "SFO": {"city": "San Francisco", "region": "California", "country": "Estados Unidos"},
    "SEA": {"city": "Seattle", "region": "Washington", "country": "Estados Unidos"},
    "LAS": {"city": "Las Vegas", "region": "Nevada", "country": "Estados Unidos"},
    "MCO": {"city": "Orlando", "region": "Florida", "country": "Estados Unidos"},
    "MIA": {"city": "Miami", "region": "Florida", "country": "Estados Unidos"},
    "FLL": {"city": "Fort Lauderdale", "region": "Florida", "country": "Estados Unidos"},
    "TPA": {"city": "Tampa", "region": "Florida", "country": "Estados Unidos"},
    "BOS": {"city": "Boston", "region": "Massachusetts", "country": "Estados Unidos"},
    "PHL": {"city": "Philadelphia", "region": "Pennsylvania", "country": "Estados Unidos"},
    "IAD": {"city": "Washington", "region": "Virginia", "country": "Estados Unidos"},
    "DCA": {"city": "Washington", "region": "Virginia", "country": "Estados Unidos"},
    "BWI": {"city": "Baltimore", "region": "Maryland", "country": "Estados Unidos"},
    "CLT": {"city": "Charlotte", "region": "North Carolina", "country": "Estados Unidos"},
    "RDU": {"city": "Raleigh-Durham", "region": "North Carolina", "country": "Estados Unidos"},
    "IAH": {"city": "Houston", "region": "Texas", "country": "Estados Unidos"},
    "HOU": {"city": "Houston", "region": "Texas", "country": "Estados Unidos"},
    "AUS": {"city": "Austin", "region": "Texas", "country": "Estados Unidos"},
    "SAT": {"city": "San Antonio", "region": "Texas", "country": "Estados Unidos"},
    "PHX": {"city": "Phoenix", "region": "Arizona", "country": "Estados Unidos"},
    "SAN": {"city": "San Diego", "region": "California", "country": "Estados Unidos"},
    "SJC": {"city": "San Jose", "region": "California", "country": "Estados Unidos"},
    "OAK": {"city": "Oakland", "region": "California", "country": "Estados Unidos"},
    "BUR": {"city": "Burbank", "region": "California", "country": "Estados Unidos"},
    "SNA": {"city": "Santa Ana", "region": "California", "country": "Estados Unidos"},
    "ONT": {"city": "Ontario", "region": "California", "country": "Estados Unidos"},
    "SMF": {"city": "Sacramento", "region": "California", "country": "Estados Unidos"},
    "PDX": {"city": "Portland", "region": "Oregon", "country": "Estados Unidos"},
    "SLC": {"city": "Salt Lake City", "region": "Utah", "country": "Estados Unidos"},
    "MSP": {"city": "Minneapolis", "region": "Minnesota", "country": "Estados Unidos"},
    "DTW": {"city": "Detroit", "region": "Michigan", "country": "Estados Unidos"},
    "CLE": {"city": "Cleveland", "region": "Ohio", "country": "Estados Unidos"},
    "CMH": {"city": "Columbus", "region": "Ohio", "country": "Estados Unidos"},
    "CVG": {"city": "Cincinnati", "region": "Kentucky", "country": "Estados Unidos"},
    "IND": {"city": "Indianapolis", "region": "Indiana", "country": "Estados Unidos"},
    "MKE": {"city": "Milwaukee", "region": "Wisconsin", "country": "Estados Unidos"},
    "STL": {"city": "St. Louis", "region": "Missouri", "country": "Estados Unidos"},
    "MCI": {"city": "Kansas City", "region": "Missouri", "country": "Estados Unidos"},
    "BNA": {"city": "Nashville", "region": "Tennessee", "country": "Estados Unidos"},
    "MEM": {"city": "Memphis", "region": "Tennessee", "country": "Estados Unidos"},
    "MSY": {"city": "New Orleans", "region": "Louisiana", "country": "Estados Unidos"},
    "PIT": {"city": "Pittsburgh", "region": "Pennsylvania", "country": "Estados Unidos"},
    "RIC": {"city": "Richmond", "region": "Virginia", "country": "Estados Unidos"},
    "ORF": {"city": "Norfolk", "region": "Virginia", "country": "Estados Unidos"},
    "JAX": {"city": "Jacksonville", "region": "Florida", "country": "Estados Unidos"},
    "RSW": {"city": "Fort Myers", "region": "Florida", "country": "Estados Unidos"},
    "CHS": {"city": "Charleston", "region": "South Carolina", "country": "Estados Unidos"},
    "SAV": {"city": "Savannah", "region": "Georgia", "country": "Estados Unidos"},
    "ABQ": {"city": "Albuquerque", "region": "New Mexico", "country": "Estados Unidos"},
    "ELP": {"city": "El Paso", "region": "Texas", "country": "Estados Unidos"},
    "TUS": {"city": "Tucson", "region": "Arizona", "country": "Estados Unidos"},
    "BOI": {"city": "Boise", "region": "Idaho", "country": "Estados Unidos"},
    "GEG": {"city": "Spokane", "region": "Washington", "country": "Estados Unidos"},
    "ANC": {"city": "Anchorage", "region": "Alaska", "country": "Estados Unidos"},
    "FAI": {"city": "Fairbanks", "region": "Alaska", "country": "Estados Unidos"},
    "HNL": {"city": "Honolulu", "region": "Hawaii", "country": "Estados Unidos"},
    "OGG": {"city": "Kahului", "region": "Hawaii", "country": "Estados Unidos"},
    "KOA": {"city": "Kailua-Kona", "region": "Hawaii", "country": "Estados Unidos"},
    "LIH": {"city": "Lihue", "region": "Hawaii", "country": "Estados Unidos"},

    # =========================
    # CANADÁ (CA)
    # =========================
    "YYZ": {"city": "Toronto", "region": "Ontario", "country": "Canadá"},
    "YTZ": {"city": "Toronto", "region": "Ontario", "country": "Canadá"},
    "YVR": {"city": "Vancouver", "region": "British Columbia", "country": "Canadá"},
    "YUL": {"city": "Montréal", "region": "Quebec", "country": "Canadá"},
    "YHU": {"city": "Montréal", "region": "Quebec", "country": "Canadá"},
    "YYC": {"city": "Calgary", "region": "Alberta", "country": "Canadá"},
    "YEG": {"city": "Edmonton", "region": "Alberta", "country": "Canadá"},
    "YOW": {"city": "Ottawa", "region": "Ontario", "country": "Canadá"},
    "YWG": {"city": "Winnipeg", "region": "Manitoba", "country": "Canadá"},
    "YHZ": {"city": "Halifax", "region": "Nova Scotia", "country": "Canadá"},
    "YQB": {"city": "Québec", "region": "Quebec", "country": "Canadá"},
    "YYJ": {"city": "Victoria", "region": "British Columbia", "country": "Canadá"},
    "YXE": {"city": "Saskatoon", "region": "Saskatchewan", "country": "Canadá"},
    "YQR": {"city": "Regina", "region": "Saskatchewan", "country": "Canadá"},
    "YYT": {"city": "St. John's", "region": "Newfoundland and Labrador", "country": "Canadá"},
    "YXY": {"city": "Whitehorse", "region": "Yukon", "country": "Canadá"},
    "YZF": {"city": "Yellowknife", "region": "Northwest Territories", "country": "Canadá"},
    "YFB": {"city": "Iqaluit", "region": "Nunavut", "country": "Canadá"},
    "YQM": {"city": "Moncton", "region": "New Brunswick", "country": "Canadá"},
    "YFC": {"city": "Fredericton", "region": "New Brunswick", "country": "Canadá"},
    "YQG": {"city": "Windsor", "region": "Ontario", "country": "Canadá"},
    "YLW": {"city": "Kelowna", "region": "British Columbia", "country": "Canadá"},
    "YKA": {"city": "Kamloops", "region": "British Columbia", "country": "Canadá"},
    "YXS": {"city": "Prince George", "region": "British Columbia", "country": "Canadá"},
    "YQT": {"city": "Thunder Bay", "region": "Ontario", "country": "Canadá"},
    "YHM": {"city": "Hamilton", "region": "Ontario", "country": "Canadá"},
    "YXU": {"city": "London", "region": "Ontario", "country": "Canadá"},

    # =========================
    # ESPAÑA (ES)
    # =========================
    "MAD": {"city": "Madrid", "region": "Comunidad de Madrid", "country": "España"},
    "BCN": {"city": "Barcelona", "region": "Cataluña", "country": "España"},
    "PMI": {"city": "Palma de Mallorca", "region": "Islas Baleares", "country": "España"},
    "AGP": {"city": "Málaga", "region": "Andalucía", "country": "España"},
    "ALC": {"city": "Alicante", "region": "Comunidad Valenciana", "country": "España"},
    "VLC": {"city": "Valencia", "region": "Comunidad Valenciana", "country": "España"},
    "SVQ": {"city": "Sevilla", "region": "Andalucía", "country": "España"},
    "BIO": {"city": "Bilbao", "region": "País Vasco", "country": "España"},
    "IBZ": {"city": "Ibiza", "region": "Islas Baleares", "country": "España"},
    "MAH": {"city": "Menorca", "region": "Islas Baleares", "country": "España"},
    "LPA": {"city": "Las Palmas de Gran Canaria", "region": "Canarias", "country": "España"},
    "TFN": {"city": "Tenerife", "region": "Canarias", "country": "España"},
    "TFS": {"city": "Tenerife", "region": "Canarias", "country": "España"},
    "ACE": {"city": "Lanzarote", "region": "Canarias", "country": "España"},
    "FUE": {"city": "Fuerteventura", "region": "Canarias", "country": "España"},
    "SPC": {"city": "Santa Cruz de La Palma", "region": "Canarias", "country": "España"},
    "VGO": {"city": "Vigo", "region": "Galicia", "country": "España"},
    "LCG": {"city": "A Coruña", "region": "Galicia", "country": "España"},
    "SCQ": {"city": "Santiago de Compostela", "region": "Galicia", "country": "España"},
    "OVD": {"city": "Asturias", "region": "Asturias", "country": "España"},
    "SDR": {"city": "Santander", "region": "Cantabria", "country": "España"},
    "ZAZ": {"city": "Zaragoza", "region": "Aragón", "country": "España"},
    "VLL": {"city": "Valladolid", "region": "Castilla y León", "country": "España"},
    "LEN": {"city": "León", "region": "Castilla y León", "country": "España"},
    "SLM": {"city": "Salamanca", "region": "Castilla y León", "country": "España"},
    "RGS": {"city": "Burgos", "region": "Castilla y León", "country": "España"},
    "BJZ": {"city": "Badajoz", "region": "Extremadura", "country": "España"},
    "MJV": {"city": "Murcia", "region": "Región de Murcia", "country": "España"},
    "RMU": {"city": "Murcia", "region": "Región de Murcia", "country": "España"},
    "GRO": {"city": "Girona", "region": "Cataluña", "country": "España"},
    "REU": {"city": "Reus", "region": "Cataluña", "country": "España"},
    "ILD": {"city": "Lleida", "region": "Cataluña", "country": "España"},
    "GRX": {"city": "Granada", "region": "Andalucía", "country": "España"},
    "LEI": {"city": "Almería", "region": "Andalucía", "country": "España"},
    "XRY": {"city": "Jerez de la Frontera", "region": "Andalucía", "country": "España"},
    "ODB": {"city": "Córdoba", "region": "Andalucía", "country": "España"},
    "PNA": {"city": "Pamplona", "region": "Navarra", "country": "España"},
    "EAS": {"city": "San Sebastián", "region": "País Vasco", "country": "España"},
    "VIT": {"city": "Vitoria-Gasteiz", "region": "País Vasco", "country": "España"},
    "MLN": {"city": "Melilla", "region": "Melilla", "country": "España"},
    "JCU": {"city": "Ceuta", "region": "Ceuta", "country": "España"},
    "ABC": {"city": "Albacete", "region": "Castilla-La Mancha", "country": "España"},
    "AEI": {"city": "Algeciras", "region": "Andalucía", "country": "España"},

    # =========================
    # BRASIL (BR)
    # =========================
    "GRU": {"city": "São Paulo", "region": "São Paulo", "country": "Brasil"},
    "CGH": {"city": "São Paulo", "region": "São Paulo", "country": "Brasil"},
    "VCP": {"city": "Campinas", "region": "São Paulo", "country": "Brasil"},
    "GIG": {"city": "Rio de Janeiro", "region": "Rio de Janeiro", "country": "Brasil"},
    "SDU": {"city": "Rio de Janeiro", "region": "Rio de Janeiro", "country": "Brasil"},
    "BSB": {"city": "Brasília", "region": "Distrito Federal", "country": "Brasil"},
    "CNF": {"city": "Belo Horizonte", "region": "Minas Gerais", "country": "Brasil"},
    "PLU": {"city": "Belo Horizonte", "region": "Minas Gerais", "country": "Brasil"},
    "SSA": {"city": "Salvador", "region": "Bahia", "country": "Brasil"},
    "REC": {"city": "Recife", "region": "Pernambuco", "country": "Brasil"},
    "FOR": {"city": "Fortaleza", "region": "Ceará", "country": "Brasil"},
    "POA": {"city": "Porto Alegre", "region": "Rio Grande do Sul", "country": "Brasil"},
    "CWB": {"city": "Curitiba", "region": "Paraná", "country": "Brasil"},
    "FLN": {"city": "Florianópolis", "region": "Santa Catarina", "country": "Brasil"},
    "NVT": {"city": "Navegantes", "region": "Santa Catarina", "country": "Brasil"},
    "JOI": {"city": "Joinville", "region": "Santa Catarina", "country": "Brasil"},
    "NAT": {"city": "Natal", "region": "Rio Grande do Norte", "country": "Brasil"},
    "MCZ": {"city": "Maceió", "region": "Alagoas", "country": "Brasil"},
    "AJU": {"city": "Aracaju", "region": "Sergipe", "country": "Brasil"},
    "BEL": {"city": "Belém", "region": "Pará", "country": "Brasil"},
    "MAO": {"city": "Manaus", "region": "Amazonas", "country": "Brasil"},
    "SLZ": {"city": "São Luís", "region": "Maranhão", "country": "Brasil"},
    "THE": {"city": "Teresina", "region": "Piauí", "country": "Brasil"},
    "CGB": {"city": "Cuiabá", "region": "Mato Grosso", "country": "Brasil"},
    "CGR": {"city": "Campo Grande", "region": "Mato Grosso do Sul", "country": "Brasil"},
    "GYN": {"city": "Goiânia", "region": "Goiás", "country": "Brasil"},
    "PMW": {"city": "Palmas", "region": "Tocantins", "country": "Brasil"},
    "PVH": {"city": "Porto Velho", "region": "Rondônia", "country": "Brasil"},
    "RBR": {"city": "Rio Branco", "region": "Acre", "country": "Brasil"},
    "BVB": {"city": "Boa Vista", "region": "Roraima", "country": "Brasil"},
    "MCP": {"city": "Macapá", "region": "Amapá", "country": "Brasil"},
    "IOS": {"city": "Ilhéus", "region": "Bahia", "country": "Brasil"},
    "BPS": {"city": "Porto Seguro", "region": "Bahia", "country": "Brasil"},
    "VIX": {"city": "Vitória", "region": "Espírito Santo", "country": "Brasil"},
    "UDI": {"city": "Uberlândia", "region": "Minas Gerais", "country": "Brasil"},
    "RAO": {"city": "Ribeirão Preto", "region": "São Paulo", "country": "Brasil"},
    "SJK": {"city": "São José dos Campos", "region": "São Paulo", "country": "Brasil"},
    "IGU": {"city": "Foz do Iguaçu", "region": "Paraná", "country": "Brasil"},
    "LDB": {"city": "Londrina", "region": "Paraná", "country": "Brasil"},
    "MGF": {"city": "Maringá", "region": "Paraná", "country": "Brasil"},
    "PET": {"city": "Pelotas", "region": "Rio Grande do Sul", "country": "Brasil"},
    "CXJ": {"city": "Caxias do Sul", "region": "Rio Grande do Sul", "country": "Brasil"},

    # =========================
    # ARGENTINA (AR)
    # =========================
    "EZE": {"city": "Buenos Aires", "region": "Buenos Aires", "country": "Argentina"},
    "AEP": {"city": "Buenos Aires", "region": "Ciudad Autónoma de Buenos Aires", "country": "Argentina"},
    "COR": {"city": "Córdoba", "region": "Córdoba", "country": "Argentina"},
    "MDZ": {"city": "Mendoza", "region": "Mendoza", "country": "Argentina"},
    "ROS": {"city": "Rosario", "region": "Santa Fe", "country": "Argentina"},
    "BRC": {"city": "San Carlos de Bariloche", "region": "Río Negro", "country": "Argentina"},
    "IGR": {"city": "Puerto Iguazú", "region": "Misiones", "country": "Argentina"},
    "SLA": {"city": "Salta", "region": "Salta", "country": "Argentina"},
    "TUC": {"city": "San Miguel de Tucumán", "region": "Tucumán", "country": "Argentina"},
    "JUJ": {"city": "San Salvador de Jujuy", "region": "Jujuy", "country": "Argentina"},
    "NQN": {"city": "Neuquén", "region": "Neuquén", "country": "Argentina"},
    "USH": {"city": "Ushuaia", "region": "Tierra del Fuego", "country": "Argentina"},
    "FTE": {"city": "El Calafate", "region": "Santa Cruz", "country": "Argentina"},
    "RGL": {"city": "Río Gallegos", "region": "Santa Cruz", "country": "Argentina"},
    "REL": {"city": "Trelew", "region": "Chubut", "country": "Argentina"},
    "PMY": {"city": "Puerto Madryn", "region": "Chubut", "country": "Argentina"},
    "CRD": {"city": "Comodoro Rivadavia", "region": "Chubut", "country": "Argentina"},
    "RSA": {"city": "Santa Rosa", "region": "La Pampa", "country": "Argentina"},
    "MDQ": {"city": "Mar del Plata", "region": "Buenos Aires", "country": "Argentina"},
    "BHI": {"city": "Bahía Blanca", "region": "Buenos Aires", "country": "Argentina"},
    "UAQ": {"city": "San Juan", "region": "San Juan", "country": "Argentina"},
    "LUQ": {"city": "San Luis", "region": "San Luis", "country": "Argentina"},
    "IRJ": {"city": "La Rioja", "region": "La Rioja", "country": "Argentina"},
    "CTC": {"city": "Catamarca", "region": "Catamarca", "country": "Argentina"},
    "RES": {"city": "Resistencia", "region": "Chaco", "country": "Argentina"},
    "CNQ": {"city": "Corrientes", "region": "Corrientes", "country": "Argentina"},
    "PSS": {"city": "Posadas", "region": "Misiones", "country": "Argentina"},
    "FMA": {"city": "Formosa", "region": "Formosa", "country": "Argentina"},

    # =========================
    # COLOMBIA (CO)
    # =========================
    "BOG": {"city": "Bogotá", "region": "Bogotá D.C.", "country": "Colombia"},
    "MDE": {"city": "Rionegro/Medellín", "region": "Antioquia", "country": "Colombia"},
    "EOH": {"city": "Medellín", "region": "Antioquia", "country": "Colombia"},
    "CLO": {"city": "Cali", "region": "Valle del Cauca", "country": "Colombia"},
    "CTG": {"city": "Cartagena", "region": "Bolívar", "country": "Colombia"},
    "BAQ": {"city": "Barranquilla", "region": "Atlántico", "country": "Colombia"},
    "SMR": {"city": "Santa Marta", "region": "Magdalena", "country": "Colombia"},
    "BGA": {"city": "Bucaramanga", "region": "Santander", "country": "Colombia"},
    "PEI": {"city": "Pereira", "region": "Risaralda", "country": "Colombia"},
    "AXM": {"city": "Armenia", "region": "Quindío", "country": "Colombia"},
    "MZL": {"city": "Manizales", "region": "Caldas", "country": "Colombia"},
    "CUC": {"city": "Cúcuta", "region": "Norte de Santander", "country": "Colombia"},
    "IBE": {"city": "Ibagué", "region": "Tolima", "country": "Colombia"},
    "NVA": {"city": "Neiva", "region": "Huila", "country": "Colombia"},
    "PSO": {"city": "Pasto", "region": "Nariño", "country": "Colombia"},
    "PPN": {"city": "Popayán", "region": "Cauca", "country": "Colombia"},
    "ADZ": {"city": "San Andrés", "region": "San Andrés y Providencia", "country": "Colombia"},
    "PVA": {"city": "Providencia", "region": "San Andrés y Providencia", "country": "Colombia"},
    "VVC": {"city": "Villavicencio", "region": "Meta", "country": "Colombia"},
    "MTR": {"city": "Montería", "region": "Córdoba", "country": "Colombia"},
    "RCH": {"city": "Riohacha", "region": "La Guajira", "country": "Colombia"},
    "VUP": {"city": "Valledupar", "region": "Cesar", "country": "Colombia"},
    "LET": {"city": "Leticia", "region": "Amazonas", "country": "Colombia"},
    "UIB": {"city": "Quibdó", "region": "Chocó", "country": "Colombia"},
    "AUC": {"city": "Arauca", "region": "Arauca", "country": "Colombia"},
    "TME": {"city": "Tame", "region": "Arauca", "country": "Colombia"},
    "EYP": {"city": "Yopal", "region": "Casanare", "country": "Colombia"},
    "FLA": {"city": "Florencia", "region": "Caquetá", "country": "Colombia"},
    "PCR": {"city": "Puerto Carreño", "region": "Vichada", "country": "Colombia"},
    "PDA": {"city": "Puerto Inírida", "region": "Guainía", "country": "Colombia"},
    "MVP": {"city": "Mitú", "region": "Vaupés", "country": "Colombia"},

    # =========================
    # CHILE (CL)
    # =========================
    "SCL": {"city": "Santiago", "region": "Región Metropolitana", "country": "Chile"},
    "ANF": {"city": "Antofagasta", "region": "Antofagasta", "country": "Chile"},
    "IQQ": {"city": "Iquique", "region": "Tarapacá", "country": "Chile"},
    "ARI": {"city": "Arica", "region": "Arica y Parinacota", "country": "Chile"},
    "CJC": {"city": "Calama", "region": "Antofagasta", "country": "Chile"},
    "CPO": {"city": "Copiapó", "region": "Atacama", "country": "Chile"},
    "LSC": {"city": "La Serena", "region": "Coquimbo", "country": "Chile"},
    "ZCO": {"city": "Temuco", "region": "La Araucanía", "country": "Chile"},
    "PMC": {"city": "Puerto Montt", "region": "Los Lagos", "country": "Chile"},
    "ZAL": {"city": "Valdivia", "region": "Los Ríos", "country": "Chile"},
    "CCP": {"city": "Concepción", "region": "Biobío", "country": "Chile"},
    "PUQ": {"city": "Punta Arenas", "region": "Magallanes", "country": "Chile"},
    "BBA": {"city": "Balmaceda", "region": "Aysén", "country": "Chile"},
    "IPC": {"city": "Isla de Pascua", "region": "Valparaíso", "country": "Chile"},
    "WPR": {"city": "Porvenir", "region": "Magallanes", "country": "Chile"},
    "WPU": {"city": "Puerto Williams", "region": "Magallanes", "country": "Chile"},
    "MHC": {"city": "Castro", "region": "Los Lagos", "country": "Chile"},

    # =========================
    # PERÚ (PE)
    # =========================
    "LIM": {"city": "Lima", "region": "Lima", "country": "Perú"},
    "CUZ": {"city": "Cusco", "region": "Cusco", "country": "Perú"},
    "AQP": {"city": "Arequipa", "region": "Arequipa", "country": "Perú"},
    "TRU": {"city": "Trujillo", "region": "La Libertad", "country": "Perú"},
    "PIU": {"city": "Piura", "region": "Piura", "country": "Perú"},
    "CIX": {"city": "Chiclayo", "region": "Lambayeque", "country": "Perú"},
    "IQT": {"city": "Iquitos", "region": "Loreto", "country": "Perú"},
    "PCL": {"city": "Pucallpa", "region": "Ucayali", "country": "Perú"},
    "TCQ": {"city": "Tacna", "region": "Tacna", "country": "Perú"},
    "JUL": {"city": "Juliaca", "region": "Puno", "country": "Perú"},
    "TPP": {"city": "Tarapoto", "region": "San Martín", "country": "Perú"},
    "PEM": {"city": "Puerto Maldonado", "region": "Madre de Dios", "country": "Perú"},
    "AYP": {"city": "Ayacucho", "region": "Ayacucho", "country": "Perú"},
    "HUU": {"city": "Huánuco", "region": "Huánuco", "country": "Perú"},
    "JAU": {"city": "Jauja", "region": "Junín", "country": "Perú"},
    "CJA": {"city": "Cajamarca", "region": "Cajamarca", "country": "Perú"},
    "TBP": {"city": "Tumbes", "region": "Tumbes", "country": "Perú"},
    "CHM": {"city": "Chimbote", "region": "Áncash", "country": "Perú"},
    "ATA": {"city": "Huaraz", "region": "Áncash", "country": "Perú"},
    "PIO": {"city": "Pisco", "region": "Ica", "country": "Perú"},
    "NZC": {"city": "Nazca", "region": "Ica", "country": "Perú"},

    # =========================
    # FRANCIA (FR)
    # =========================
    "CDG": {"city": "París", "region": "Île-de-France", "country": "Francia"},
    "ORY": {"city": "París", "region": "Île-de-France", "country": "Francia"},
    "BVA": {"city": "Beauvais", "region": "Hauts-de-France", "country": "Francia"},
    "LYS": {"city": "Lyon", "region": "Auvergne-Rhône-Alpes", "country": "Francia"},
    "MRS": {"city": "Marsella", "region": "Provence-Alpes-Côte d’Azur", "country": "Francia"},
    "NCE": {"city": "Niza", "region": "Provence-Alpes-Côte d’Azur", "country": "Francia"},
    "TLS": {"city": "Toulouse", "region": "Occitania", "country": "Francia"},
    "BOD": {"city": "Burdeos", "region": "Nueva Aquitania", "country": "Francia"},
    "NTE": {"city": "Nantes", "region": "Países del Loira", "country": "Francia"},
    "LIL": {"city": "Lille", "region": "Hauts-de-France", "country": "Francia"},
    "SXB": {"city": "Estrasburgo", "region": "Gran Este", "country": "Francia"},
    "MPL": {"city": "Montpellier", "region": "Occitania", "country": "Francia"},
    "RNS": {"city": "Rennes", "region": "Bretaña", "country": "Francia"},
    "BIQ": {"city": "Biarritz", "region": "Nueva Aquitania", "country": "Francia"},
    "AJA": {"city": "Ajaccio", "region": "Córcega", "country": "Francia"},
    "BIA": {"city": "Bastia", "region": "Córcega", "country": "Francia"},
    "FSC": {"city": "Figari", "region": "Córcega", "country": "Francia"},
    "CLY": {"city": "Calvi", "region": "Córcega", "country": "Francia"},
    "CFE": {"city": "Clermont-Ferrand", "region": "Auvergne-Rhône-Alpes", "country": "Francia"},
    "GNB": {"city": "Grenoble", "region": "Auvergne-Rhône-Alpes", "country": "Francia"},
    "ETZ": {"city": "Metz/Nancy", "region": "Gran Este", "country": "Francia"},
    "TLN": {"city": "Toulon", "region": "Provence-Alpes-Côte d’Azur", "country": "Francia"},
    "PUF": {"city": "Pau", "region": "Nueva Aquitania", "country": "Francia"},
    "LDE": {"city": "Lourdes/Tarbes", "region": "Occitania", "country": "Francia"},

    # =========================
    # ALEMANIA (DE)
    # =========================
    "FRA": {"city": "Fráncfort", "region": "Hesse", "country": "Alemania"},
    "MUC": {"city": "Múnich", "region": "Baviera", "country": "Alemania"},
    "BER": {"city": "Berlín", "region": "Berlín/Brandeburgo", "country": "Alemania"},
    "HAM": {"city": "Hamburgo", "region": "Hamburgo", "country": "Alemania"},
    "DUS": {"city": "Düsseldorf", "region": "Renania del Norte-Westfalia", "country": "Alemania"},
    "CGN": {"city": "Colonia/Bonn", "region": "Renania del Norte-Westfalia", "country": "Alemania"},
    "STR": {"city": "Stuttgart", "region": "Baden-Württemberg", "country": "Alemania"},
    "HAJ": {"city": "Hannover", "region": "Baja Sajonia", "country": "Alemania"},
    "NUE": {"city": "Núremberg", "region": "Baviera", "country": "Alemania"},
    "LEJ": {"city": "Leipzig/Halle", "region": "Sajonia", "country": "Alemania"},
    "DRS": {"city": "Dresde", "region": "Sajonia", "country": "Alemania"},
    "BRE": {"city": "Bremen", "region": "Bremen", "country": "Alemania"},
    "DTM": {"city": "Dortmund", "region": "Renania del Norte-Westfalia", "country": "Alemania"},
    "FMO": {"city": "Münster/Osnabrück", "region": "Renania del Norte-Westfalia", "country": "Alemania"},
    "FKB": {"city": "Karlsruhe/Baden-Baden", "region": "Baden-Württemberg", "country": "Alemania"},
    "NRN": {"city": "Weeze", "region": "Renania del Norte-Westfalia", "country": "Alemania"},
    "SCN": {"city": "Saarbrücken", "region": "Sarre", "country": "Alemania"},
    "PAD": {"city": "Paderborn/Lippstadt", "region": "Renania del Norte-Westfalia", "country": "Alemania"},
    "FDH": {"city": "Friedrichshafen", "region": "Baden-Württemberg", "country": "Alemania"},
    "ERF": {"city": "Erfurt", "region": "Turingia", "country": "Alemania"},

    # =========================
    # ITALIA (IT)
    # =========================
    "FCO": {"city": "Roma", "region": "Lacio", "country": "Italia"},
    "CIA": {"city": "Roma", "region": "Lacio", "country": "Italia"},
    "MXP": {"city": "Milán", "region": "Lombardía", "country": "Italia"},
    "LIN": {"city": "Milán", "region": "Lombardía", "country": "Italia"},
    "BGY": {"city": "Bérgamo/Milán", "region": "Lombardía", "country": "Italia"},
    "VCE": {"city": "Venecia", "region": "Véneto", "country": "Italia"},
    "TSF": {"city": "Treviso", "region": "Véneto", "country": "Italia"},
    "NAP": {"city": "Nápoles", "region": "Campania", "country": "Italia"},
    "CTA": {"city": "Catania", "region": "Sicilia", "country": "Italia"},
    "PMO": {"city": "Palermo", "region": "Sicilia", "country": "Italia"},
    "BLQ": {"city": "Bolonia", "region": "Emilia-Romaña", "country": "Italia"},
    "FLR": {"city": "Florencia", "region": "Toscana", "country": "Italia"},
    "PSA": {"city": "Pisa", "region": "Toscana", "country": "Italia"},
    "TRN": {"city": "Turín", "region": "Piamonte", "country": "Italia"},
    "GOA": {"city": "Génova", "region": "Liguria", "country": "Italia"},
    "BRI": {"city": "Bari", "region": "Apulia", "country": "Italia"},
    "BDS": {"city": "Bríndisi", "region": "Apulia", "country": "Italia"},
    "CAG": {"city": "Cagliari", "region": "Cerdeña", "country": "Italia"},
    "OLB": {"city": "Olbia", "region": "Cerdeña", "country": "Italia"},
    "AHO": {"city": "Alghero", "region": "Cerdeña", "country": "Italia"},
    "VRN": {"city": "Verona", "region": "Véneto", "country": "Italia"},
    "TRS": {"city": "Trieste", "region": "Friuli-Venecia Julia", "country": "Italia"},
    "SUF": {"city": "Lamezia Terme", "region": "Calabria", "country": "Italia"},
    "REG": {"city": "Reggio Calabria", "region": "Calabria", "country": "Italia"},
    "PEG": {"city": "Perugia", "region": "Umbría", "country": "Italia"},
    "AOI": {"city": "Ancona", "region": "Marcas", "country": "Italia"},
    "PSR": {"city": "Pescara", "region": "Abruzos", "country": "Italia"},

    # =========================
    # REINO UNIDO (GB)
    # =========================
    "LHR": {"city": "Londres", "region": "Inglaterra", "country": "Reino Unido"},
    "LGW": {"city": "Londres", "region": "Inglaterra", "country": "Reino Unido"},
    "STN": {"city": "Londres", "region": "Inglaterra", "country": "Reino Unido"},
    "LTN": {"city": "Londres", "region": "Inglaterra", "country": "Reino Unido"},
    "LCY": {"city": "Londres", "region": "Inglaterra", "country": "Reino Unido"},
    "SEN": {"city": "Southend-on-Sea", "region": "Inglaterra", "country": "Reino Unido"},
    "MAN": {"city": "Manchester", "region": "Inglaterra", "country": "Reino Unido"},
    "BHX": {"city": "Birmingham", "region": "Inglaterra", "country": "Reino Unido"},
    "EDI": {"city": "Edimburgo", "region": "Escocia", "country": "Reino Unido"},
    "GLA": {"city": "Glasgow", "region": "Escocia", "country": "Reino Unido"},
    "ABZ": {"city": "Aberdeen", "region": "Escocia", "country": "Reino Unido"},
    "INV": {"city": "Inverness", "region": "Escocia", "country": "Reino Unido"},
    "BFS": {"city": "Belfast", "region": "Irlanda del Norte", "country": "Reino Unido"},
    "BHD": {"city": "Belfast", "region": "Irlanda del Norte", "country": "Reino Unido"},
    "CWL": {"city": "Cardiff", "region": "Gales", "country": "Reino Unido"},
    "BRS": {"city": "Bristol", "region": "Inglaterra", "country": "Reino Unido"},
    "NCL": {"city": "Newcastle upon Tyne", "region": "Inglaterra", "country": "Reino Unido"},
    "LPL": {"city": "Liverpool", "region": "Inglaterra", "country": "Reino Unido"},
    "LBA": {"city": "Leeds/Bradford", "region": "Inglaterra", "country": "Reino Unido"},
    "EMA": {"city": "East Midlands", "region": "Inglaterra", "country": "Reino Unido"},
    "SOU": {"city": "Southampton", "region": "Inglaterra", "country": "Reino Unido"},
    "BOH": {"city": "Bournemouth", "region": "Inglaterra", "country": "Reino Unido"},
    "EXT": {"city": "Exeter", "region": "Inglaterra", "country": "Reino Unido"},
    "NWI": {"city": "Norwich", "region": "Inglaterra", "country": "Reino Unido"},
    "HUY": {"city": "Humberside", "region": "Inglaterra", "country": "Reino Unido"},
    "MME": {"city": "Teesside", "region": "Inglaterra", "country": "Reino Unido"},
    "DSA": {"city": "Doncaster/Sheffield", "region": "Inglaterra", "country": "Reino Unido"},
    "JER": {"city": "Jersey", "region": "Jersey", "country": "Reino Unido"},
    "GCI": {"city": "Guernsey", "region": "Guernsey", "country": "Reino Unido"},
    "IOM": {"city": "Isle of Man", "region": "Isle of Man", "country": "Reino Unido"},

    # =========================
    # JAPÓN (JP)
    # =========================
    "HND": {"city": "Tokio", "region": "Tokio", "country": "Japón"},
    "NRT": {"city": "Narita/Tokio", "region": "Chiba", "country": "Japón"},
    "KIX": {"city": "Osaka", "region": "Osaka", "country": "Japón"},
    "ITM": {"city": "Osaka", "region": "Osaka", "country": "Japón"},
    "UKB": {"city": "Kobe", "region": "Hyogo", "country": "Japón"},
    "CTS": {"city": "Sapporo", "region": "Hokkaido", "country": "Japón"},
    "OKD": {"city": "Sapporo", "region": "Hokkaido", "country": "Japón"},
    "FUK": {"city": "Fukuoka", "region": "Fukuoka", "country": "Japón"},
    "NGO": {"city": "Nagoya", "region": "Aichi", "country": "Japón"},
    "NKM": {"city": "Nagoya", "region": "Aichi", "country": "Japón"},
    "OKA": {"city": "Naha", "region": "Okinawa", "country": "Japón"},
    "SDJ": {"city": "Sendai", "region": "Miyagi", "country": "Japón"},
    "HIJ": {"city": "Hiroshima", "region": "Hiroshima", "country": "Japón"},
    "KOJ": {"city": "Kagoshima", "region": "Kagoshima", "country": "Japón"},
    "KMJ": {"city": "Kumamoto", "region": "Kumamoto", "country": "Japón"},
    "NGS": {"city": "Nagasaki", "region": "Nagasaki", "country": "Japón"},
    "OIT": {"city": "Oita", "region": "Oita", "country": "Japón"},
    "KMI": {"city": "Miyazaki", "region": "Miyazaki", "country": "Japón"},
    "MYJ": {"city": "Matsuyama", "region": "Ehime", "country": "Japón"},
    "TAK": {"city": "Takamatsu", "region": "Kagawa", "country": "Japón"},
    "KCZ": {"city": "Kochi", "region": "Kochi", "country": "Japón"},
    "TKS": {"city": "Tokushima", "region": "Tokushima", "country": "Japón"},
    "KMQ": {"city": "Komatsu", "region": "Ishikawa", "country": "Japón"},
    "TOY": {"city": "Toyama", "region": "Toyama", "country": "Japón"},
    "KIJ": {"city": "Niigata", "region": "Niigata", "country": "Japón"},
    "GAJ": {"city": "Yamagata", "region": "Yamagata", "country": "Japón"},
    "AXT": {"city": "Akita", "region": "Akita", "country": "Japón"},
    "AOJ": {"city": "Aomori", "region": "Aomori", "country": "Japón"},
    "MSJ": {"city": "Misawa", "region": "Aomori", "country": "Japón"},
    "HNA": {"city": "Morioka/Hanamaki", "region": "Iwate", "country": "Japón"},
    "FKS": {"city": "Fukushima", "region": "Fukushima", "country": "Japón"},
    "IBR": {"city": "Ibaraki", "region": "Ibaraki", "country": "Japón"},
    "MMJ": {"city": "Matsumoto", "region": "Nagano", "country": "Japón"},
    "FSZ": {"city": "Shizuoka", "region": "Shizuoka", "country": "Japón"},
    "YGJ": {"city": "Yonago", "region": "Tottori", "country": "Japón"},
    "TTJ": {"city": "Tottori", "region": "Tottori", "country": "Japón"},
    "IZO": {"city": "Izumo", "region": "Shimane", "country": "Japón"},
    "IWJ": {"city": "Iwami", "region": "Shimane", "country": "Japón"},
    "OKJ": {"city": "Okayama", "region": "Okayama", "country": "Japón"},
    "UBJ": {"city": "Ube", "region": "Yamaguchi", "country": "Japón"},
    "KKJ": {"city": "Kitakyushu", "region": "Fukuoka", "country": "Japón"},
    "HSG": {"city": "Saga", "region": "Saga", "country": "Japón"},
    "TSJ": {"city": "Tsushima", "region": "Nagasaki", "country": "Japón"},
    "IKI": {"city": "Iki", "region": "Nagasaki", "country": "Japón"},
    "FUJ": {"city": "Gotō", "region": "Nagasaki", "country": "Japón"},
    "ASJ": {"city": "Amami", "region": "Kagoshima", "country": "Japón"},
    "TNE": {"city": "Tanegashima", "region": "Kagoshima", "country": "Japón"},
    "KUM": {"city": "Yakushima", "region": "Kagoshima", "country": "Japón"},
    "OKE": {"city": "Okinoerabu", "region": "Kagoshima", "country": "Japón"},
    "RNJ": {"city": "Yoron", "region": "Kagoshima", "country": "Japón"},
    "ISG": {"city": "Ishigaki", "region": "Okinawa", "country": "Japón"},
    "MMY": {"city": "Miyakojima", "region": "Okinawa", "country": "Japón"},
    "UEO": {"city": "Kumejima", "region": "Okinawa", "country": "Japón"},
    "TRA": {"city": "Tarama", "region": "Okinawa", "country": "Japón"},
    "KTD": {"city": "Kitadaito", "region": "Okinawa", "country": "Japón"},
    "MMD": {"city": "Minamidaito", "region": "Okinawa", "country": "Japón"},
    "AGJ": {"city": "Aguni", "region": "Okinawa", "country": "Japón"},
    "AXJ": {"city": "Amakusa", "region": "Kumamoto", "country": "Japón"},
    "NJA": {"city": "Atsugi", "region": "Kanagawa", "country": "Japón"},
    "FKJ": {"city": "Fukui", "region": "Fukui", "country": "Japón"},
    "QFY": {"city": "Fukuyama", "region": "Hiroshima", "country": "Japón"},
    "QGU": {"city": "Gifu", "region": "Gifu", "country": "Japón"},
    # =========================
    # PORTUGAL (PT)
    # =========================
    "LIS": {"city": "Lisboa", "region": "Lisboa", "country": "Portugal"},
    "OPO": {"city": "Porto", "region": "Porto", "country": "Portugal"},
    "FAO": {"city": "Faro", "region": "Algarve", "country": "Portugal"},
    "FNC": {"city": "Funchal", "region": "Madeira", "country": "Portugal"},
    "PXO": {"city": "Porto Santo", "region": "Madeira", "country": "Portugal"},
    "PDL": {"city": "Ponta Delgada", "region": "Azores", "country": "Portugal"},
    "TER": {"city": "Terceira/Lajes", "region": "Azores", "country": "Portugal"},
    "HOR": {"city": "Horta", "region": "Azores", "country": "Portugal"},
    "PIX": {"city": "Pico", "region": "Azores", "country": "Portugal"},
    "SMA": {"city": "Santa Maria", "region": "Azores", "country": "Portugal"},
    "VRL": {"city": "Vila Real", "region": "Vila Real", "country": "Portugal"},
    "BGC": {"city": "Bragança", "region": "Bragança", "country": "Portugal"},

    # =========================
    # PAÍSES BAJOS (NL)
    # =========================
    "AMS": {"city": "Ámsterdam", "region": "Holanda Septentrional", "country": "Países Bajos"},
    "RTM": {"city": "Róterdam", "region": "Holanda Meridional", "country": "Países Bajos"},
    "EIN": {"city": "Eindhoven", "region": "Brabante Septentrional", "country": "Países Bajos"},
    "MST": {"city": "Maastricht", "region": "Limburgo", "country": "Países Bajos"},
    "GRQ": {"city": "Groninga", "region": "Groninga", "country": "Países Bajos"},
    "LEY": {"city": "Lelystad", "region": "Flevoland", "country": "Países Bajos"},

    # =========================
    # BÉLGICA (BE)
    # =========================
    "BRU": {"city": "Bruselas", "region": "Brabante Flamenco", "country": "Bélgica"},
    "CRL": {"city": "Charleroi", "region": "Valonia", "country": "Bélgica"},
    "ANR": {"city": "Amberes", "region": "Flandes", "country": "Bélgica"},
    "OST": {"city": "Ostende", "region": "Flandes Occidental", "country": "Bélgica"},
    "LGG": {"city": "Lieja", "region": "Valonia", "country": "Bélgica"},
    "KJK": {"city": "Kortrijk", "region": "Flandes Occidental", "country": "Bélgica"},

    # =========================
    # SUIZA (CH)
    # =========================
    "ZRH": {"city": "Zúrich", "region": "Zúrich", "country": "Suiza"},
    "GVA": {"city": "Ginebra", "region": "Ginebra", "country": "Suiza"},
    "BSL": {"city": "Basilea", "region": "Basilea-Ciudad", "country": "Suiza"},
    "BRN": {"city": "Berna", "region": "Berna", "country": "Suiza"},
    "LUG": {"city": "Lugano", "region": "Tesino", "country": "Suiza"},
    "SIR": {"city": "Sion", "region": "Valais", "country": "Suiza"},
    "ACH": {"city": "Altenrhein", "region": "San Galo", "country": "Suiza"},

    # =========================
    # AUSTRIA (AT)
    # =========================
    "VIE": {"city": "Viena", "region": "Viena", "country": "Austria"},
    "SZG": {"city": "Salzburgo", "region": "Salzburgo", "country": "Austria"},
    "INN": {"city": "Innsbruck", "region": "Tirol", "country": "Austria"},
    "GRZ": {"city": "Graz", "region": "Estiria", "country": "Austria"},
    "LNZ": {"city": "Linz", "region": "Alta Austria", "country": "Austria"},
    "KLU": {"city": "Klagenfurt", "region": "Carintia", "country": "Austria"},

    # =========================
    # IRLANDA (IE)
    # =========================
    "DUB": {"city": "Dublín", "region": "Leinster", "country": "Irlanda"},
    "ORK": {"city": "Cork", "region": "Munster", "country": "Irlanda"},
    "SNN": {"city": "Shannon", "region": "Munster", "country": "Irlanda"},
    "NOC": {"city": "Knock", "region": "Connacht", "country": "Irlanda"},
    "KIR": {"city": "Kerry", "region": "Munster", "country": "Irlanda"},
    "CFN": {"city": "Donegal", "region": "Ulster", "country": "Irlanda"},
    "WAT": {"city": "Waterford", "region": "Munster", "country": "Irlanda"},

    # =========================
    # NORUEGA (NO)
    # =========================
    "OSL": {"city": "Oslo", "region": "Akershus", "country": "Noruega"},
    "TRF": {"city": "Sandefjord", "region": "Vestfold", "country": "Noruega"},
    "BGO": {"city": "Bergen", "region": "Vestland", "country": "Noruega"},
    "SVG": {"city": "Stavanger", "region": "Rogaland", "country": "Noruega"},
    "TRD": {"city": "Trondheim", "region": "Trøndelag", "country": "Noruega"},
    "TOS": {"city": "Tromsø", "region": "Troms", "country": "Noruega"},
    "BOO": {"city": "Bodø", "region": "Nordland", "country": "Noruega"},
    "AES": {"city": "Ålesund", "region": "Møre og Romsdal", "country": "Noruega"},
    "KRS": {"city": "Kristiansand", "region": "Agder", "country": "Noruega"},
    "HAU": {"city": "Haugesund", "region": "Rogaland", "country": "Noruega"},
    "ALF": {"city": "Alta", "region": "Finnmark", "country": "Noruega"},
    "KKN": {"city": "Kirkenes", "region": "Finnmark", "country": "Noruega"},

    # =========================
    # SUECIA (SE)
    # =========================
    "ARN": {"city": "Estocolmo", "region": "Estocolmo", "country": "Suecia"},
    "BMA": {"city": "Estocolmo", "region": "Estocolmo", "country": "Suecia"},
    "GOT": {"city": "Gotemburgo", "region": "Västra Götaland", "country": "Suecia"},
    "MMX": {"city": "Malmö", "region": "Escania", "country": "Suecia"},
    "NYO": {"city": "Nyköping", "region": "Södermanland", "country": "Suecia"},
    "VST": {"city": "Västerås", "region": "Västmanland", "country": "Suecia"},
    "LLA": {"city": "Luleå", "region": "Norrbotten", "country": "Suecia"},
    "UME": {"city": "Umeå", "region": "Västerbotten", "country": "Suecia"},
    "KRN": {"city": "Kiruna", "region": "Norrbotten", "country": "Suecia"},
    "OSD": {"city": "Östersund", "region": "Jämtland", "country": "Suecia"},

    # =========================
    # DINAMARCA (DK)
    # =========================
    "CPH": {"city": "Copenhague", "region": "Región Capital", "country": "Dinamarca"},
    "BLL": {"city": "Billund", "region": "Dinamarca Meridional", "country": "Dinamarca"},
    "AAL": {"city": "Aalborg", "region": "Jutlandia Septentrional", "country": "Dinamarca"},
    "AAR": {"city": "Aarhus", "region": "Jutlandia Central", "country": "Dinamarca"},
    "RNN": {"city": "Rønne", "region": "Bornholm", "country": "Dinamarca"},
    "EBJ": {"city": "Esbjerg", "region": "Dinamarca Meridional", "country": "Dinamarca"},
    "SGD": {"city": "Sønderborg", "region": "Dinamarca Meridional", "country": "Dinamarca"},

    # =========================
    # FINLANDIA (FI)
    # =========================
    "HEL": {"city": "Helsinki", "region": "Uusimaa", "country": "Finlandia"},
    "TMP": {"city": "Tampere", "region": "Pirkanmaa", "country": "Finlandia"},
    "TKU": {"city": "Turku", "region": "Finlandia Propia", "country": "Finlandia"},
    "OUL": {"city": "Oulu", "region": "Ostrobotnia del Norte", "country": "Finlandia"},
    "RVN": {"city": "Rovaniemi", "region": "Laponia", "country": "Finlandia"},
    "KTT": {"city": "Kittilä", "region": "Laponia", "country": "Finlandia"},
    "IVL": {"city": "Ivalo", "region": "Laponia", "country": "Finlandia"},
    "KUO": {"city": "Kuopio", "region": "Savonia del Norte", "country": "Finlandia"},
    "VAA": {"city": "Vaasa", "region": "Ostrobotnia", "country": "Finlandia"},
    "JOE": {"city": "Joensuu", "region": "Karelia del Norte", "country": "Finlandia"},

    # =========================
    # POLONIA (PL)
    # =========================
    "WAW": {"city": "Varsovia", "region": "Mazovia", "country": "Polonia"},
    "WMI": {"city": "Modlin", "region": "Mazovia", "country": "Polonia"},
    "KRK": {"city": "Cracovia", "region": "Pequeña Polonia", "country": "Polonia"},
    "GDN": {"city": "Gdańsk", "region": "Pomerania", "country": "Polonia"},
    "KTW": {"city": "Katowice", "region": "Silesia", "country": "Polonia"},
    "WRO": {"city": "Wrocław", "region": "Baja Silesia", "country": "Polonia"},
    "POZ": {"city": "Poznań", "region": "Gran Polonia", "country": "Polonia"},
    "RZE": {"city": "Rzeszów", "region": "Subcarpacia", "country": "Polonia"},
    "SZZ": {"city": "Szczecin", "region": "Pomerania Occidental", "country": "Polonia"},
    "LCJ": {"city": "Łódź", "region": "Łódź", "country": "Polonia"},
    "BZG": {"city": "Bydgoszcz", "region": "Cuyavia-Pomerania", "country": "Polonia"},
    "LUZ": {"city": "Lublin", "region": "Lublin", "country": "Polonia"},

    # =========================
    # REPÚBLICA CHECA / CHEQUIA (CZ)
    # =========================
    "PRG": {"city": "Praga", "region": "Praga", "country": "República Checa"},
    "BRQ": {"city": "Brno", "region": "Moravia Meridional", "country": "República Checa"},
    "OSR": {"city": "Ostrava", "region": "Moravia-Silesia", "country": "República Checa"},
    "KLV": {"city": "Karlovy Vary", "region": "Karlovy Vary", "country": "República Checa"},
    "PED": {"city": "Pardubice", "region": "Pardubice", "country": "República Checa"},

    # =========================
    # GRECIA (GR)
    # =========================
    "ATH": {"city": "Atenas", "region": "Ática", "country": "Grecia"},
    "SKG": {"city": "Tesalónica", "region": "Macedonia Central", "country": "Grecia"},
    "HER": {"city": "Heraklion", "region": "Creta", "country": "Grecia"},
    "CHQ": {"city": "Chania", "region": "Creta", "country": "Grecia"},
    "RHO": {"city": "Rodas", "region": "Egeo Meridional", "country": "Grecia"},
    "CFU": {"city": "Corfú", "region": "Islas Jónicas", "country": "Grecia"},
    "JMK": {"city": "Mikonos", "region": "Egeo Meridional", "country": "Grecia"},
    "JTR": {"city": "Santorini", "region": "Egeo Meridional", "country": "Grecia"},
    "KGS": {"city": "Kos", "region": "Egeo Meridional", "country": "Grecia"},
    "ZTH": {"city": "Zante", "region": "Islas Jónicas", "country": "Grecia"},
    "PVK": {"city": "Preveza", "region": "Epiro", "country": "Grecia"},
    "KLX": {"city": "Kalamata", "region": "Peloponeso", "country": "Grecia"},

    # =========================
    # TURQUÍA (TR)
    # =========================
    "IST": {"city": "Estambul", "region": "Estambul", "country": "Turquía"},
    "SAW": {"city": "Estambul", "region": "Estambul", "country": "Turquía"},
    "ESB": {"city": "Ankara", "region": "Ankara", "country": "Turquía"},
    "ADB": {"city": "Esmirna", "region": "Esmirna", "country": "Turquía"},
    "AYT": {"city": "Antalya", "region": "Antalya", "country": "Turquía"},
    "DLM": {"city": "Dalaman", "region": "Muğla", "country": "Turquía"},
    "BJV": {"city": "Bodrum", "region": "Muğla", "country": "Turquía"},
    "ADA": {"city": "Adana", "region": "Adana", "country": "Turquía"},
    "TZX": {"city": "Trabzon", "region": "Trabzon", "country": "Turquía"},
    "ASR": {"city": "Kayseri", "region": "Kayseri", "country": "Turquía"},
    "GZT": {"city": "Gaziantep", "region": "Gaziantep", "country": "Turquía"},
    "DIY": {"city": "Diyarbakır", "region": "Diyarbakır", "country": "Turquía"},
    "ERZ": {"city": "Erzurum", "region": "Erzurum", "country": "Turquía"},
    "VAN": {"city": "Van", "region": "Van", "country": "Turquía"},

    # =========================
    # RUSIA (RU)
    # =========================
    "SVO": {"city": "Moscú", "region": "Moscú", "country": "Rusia"},
    "DME": {"city": "Moscú", "region": "Moscú", "country": "Rusia"},
    "VKO": {"city": "Moscú", "region": "Moscú", "country": "Rusia"},
    "LED": {"city": "San Petersburgo", "region": "San Petersburgo", "country": "Rusia"},
    "AER": {"city": "Sochi", "region": "Krasnodar", "country": "Rusia"},
    "KZN": {"city": "Kazán", "region": "Tartaristán", "country": "Rusia"},
    "SVX": {"city": "Ekaterimburgo", "region": "Sverdlovsk", "country": "Rusia"},
    "OVB": {"city": "Novosibirsk", "region": "Novosibirsk", "country": "Rusia"},
    "ROV": {"city": "Rostov del Don", "region": "Rostov", "country": "Rusia"},
    "KRR": {"city": "Krasnodar", "region": "Krasnodar", "country": "Rusia"},
    "UFA": {"city": "Ufá", "region": "Bashkortostán", "country": "Rusia"},
    "KUF": {"city": "Samara", "region": "Samara", "country": "Rusia"},
    "CEK": {"city": "Cheliábinsk", "region": "Cheliábinsk", "country": "Rusia"},
    "VVO": {"city": "Vladivostok", "region": "Primorie", "country": "Rusia"},
    "IKT": {"city": "Irkutsk", "region": "Irkutsk", "country": "Rusia"},

    # =========================
    # CHINA (CN)
    # =========================
    "PEK": {"city": "Pekín", "region": "Pekín", "country": "China"},
    "PKX": {"city": "Pekín", "region": "Pekín", "country": "China"},
    "PVG": {"city": "Shanghái", "region": "Shanghái", "country": "China"},
    "SHA": {"city": "Shanghái", "region": "Shanghái", "country": "China"},
    "CAN": {"city": "Guangzhou", "region": "Guangdong", "country": "China"},
    "SZX": {"city": "Shenzhen", "region": "Guangdong", "country": "China"},
    "CTU": {"city": "Chengdu", "region": "Sichuan", "country": "China"},
    "TFU": {"city": "Chengdu", "region": "Sichuan", "country": "China"},
    "XIY": {"city": "Xi'an", "region": "Shaanxi", "country": "China"},
    "KMG": {"city": "Kunming", "region": "Yunnan", "country": "China"},
    "HGH": {"city": "Hangzhou", "region": "Zhejiang", "country": "China"},
    "NKG": {"city": "Nankín", "region": "Jiangsu", "country": "China"},
    "WUH": {"city": "Wuhan", "region": "Hubei", "country": "China"},
    "CKG": {"city": "Chongqing", "region": "Chongqing", "country": "China"},
    "XMN": {"city": "Xiamen", "region": "Fujian", "country": "China"},
    "TAO": {"city": "Qingdao", "region": "Shandong", "country": "China"},
    "DLC": {"city": "Dalian", "region": "Liaoning", "country": "China"},
    "TSN": {"city": "Tianjin", "region": "Tianjin", "country": "China"},
    "CGO": {"city": "Zhengzhou", "region": "Henan", "country": "China"},
    "CSX": {"city": "Changsha", "region": "Hunan", "country": "China"},

    # =========================
    # INDIA (IN)
    # =========================
    "DEL": {"city": "Nueva Delhi", "region": "Delhi", "country": "India"},
    "BOM": {"city": "Mumbai", "region": "Maharashtra", "country": "India"},
    "BLR": {"city": "Bangalore", "region": "Karnataka", "country": "India"},
    "MAA": {"city": "Chennai", "region": "Tamil Nadu", "country": "India"},
    "HYD": {"city": "Hyderabad", "region": "Telangana", "country": "India"},
    "CCU": {"city": "Calcuta", "region": "Bengala Occidental", "country": "India"},
    "AMD": {"city": "Ahmedabad", "region": "Gujarat", "country": "India"},
    "COK": {"city": "Kochi", "region": "Kerala", "country": "India"},
    "GOI": {"city": "Goa", "region": "Goa", "country": "India"},
    "PNQ": {"city": "Pune", "region": "Maharashtra", "country": "India"},
    "JAI": {"city": "Jaipur", "region": "Rajasthan", "country": "India"},
    "LKO": {"city": "Lucknow", "region": "Uttar Pradesh", "country": "India"},
    "TRV": {"city": "Thiruvananthapuram", "region": "Kerala", "country": "India"},
    "IXC": {"city": "Chandigarh", "region": "Chandigarh", "country": "India"},
    "BBI": {"city": "Bhubaneswar", "region": "Odisha", "country": "India"},
    "GAU": {"city": "Guwahati", "region": "Assam", "country": "India"},
    "ATQ": {"city": "Amritsar", "region": "Punjab", "country": "India"},

    # =========================
    # COREA DEL SUR (KR)
    # =========================
    "ICN": {"city": "Seúl/Incheon", "region": "Incheon", "country": "Corea del Sur"},
    "GMP": {"city": "Seúl", "region": "Seúl", "country": "Corea del Sur"},
    "PUS": {"city": "Busan", "region": "Busan", "country": "Corea del Sur"},
    "CJU": {"city": "Jeju", "region": "Jeju", "country": "Corea del Sur"},
    "TAE": {"city": "Daegu", "region": "Daegu", "country": "Corea del Sur"},
    "CJJ": {"city": "Cheongju", "region": "Chungcheong del Norte", "country": "Corea del Sur"},
    "KWJ": {"city": "Gwangju", "region": "Gwangju", "country": "Corea del Sur"},
    "USN": {"city": "Ulsan", "region": "Ulsan", "country": "Corea del Sur"},
    "RSU": {"city": "Yeosu", "region": "Jeolla del Sur", "country": "Corea del Sur"},
    "YNY": {"city": "Yangyang", "region": "Gangwon", "country": "Corea del Sur"},

    # =========================
    # TAILANDIA (TH)
    # =========================
    "BKK": {"city": "Bangkok", "region": "Bangkok", "country": "Tailandia"},
    "DMK": {"city": "Bangkok", "region": "Bangkok", "country": "Tailandia"},
    "HKT": {"city": "Phuket", "region": "Phuket", "country": "Tailandia"},
    "CNX": {"city": "Chiang Mai", "region": "Chiang Mai", "country": "Tailandia"},
    "KBV": {"city": "Krabi", "region": "Krabi", "country": "Tailandia"},
    "USM": {"city": "Koh Samui", "region": "Surat Thani", "country": "Tailandia"},
    "HDY": {"city": "Hat Yai", "region": "Songkhla", "country": "Tailandia"},
    "CEI": {"city": "Chiang Rai", "region": "Chiang Rai", "country": "Tailandia"},
    "UTH": {"city": "Udon Thani", "region": "Udon Thani", "country": "Tailandia"},
    "URT": {"city": "Surat Thani", "region": "Surat Thani", "country": "Tailandia"},
    "PHS": {"city": "Phitsanulok", "region": "Phitsanulok", "country": "Tailandia"},
    "UTP": {"city": "Rayong/Pattaya", "region": "Rayong", "country": "Tailandia"},

    # =========================
    # SINGAPUR (SG)
    # =========================
    "SIN": {"city": "Singapur", "region": "Singapur", "country": "Singapur"},
    "XSP": {"city": "Seletar", "region": "Singapur", "country": "Singapur"},

    # =========================
    # MALASIA (MY)
    # =========================
    "KUL": {"city": "Kuala Lumpur", "region": "Selangor", "country": "Malasia"},
    "SZB": {"city": "Subang", "region": "Selangor", "country": "Malasia"},
    "PEN": {"city": "Penang", "region": "Penang", "country": "Malasia"},
    "JHB": {"city": "Johor Bahru", "region": "Johor", "country": "Malasia"},
    "LGK": {"city": "Langkawi", "region": "Kedah", "country": "Malasia"},
    "KCH": {"city": "Kuching", "region": "Sarawak", "country": "Malasia"},
    "BKI": {"city": "Kota Kinabalu", "region": "Sabah", "country": "Malasia"},
    "MYY": {"city": "Miri", "region": "Sarawak", "country": "Malasia"},
    "KBR": {"city": "Kota Bharu", "region": "Kelantan", "country": "Malasia"},
    "TGG": {"city": "Kuala Terengganu", "region": "Terengganu", "country": "Malasia"},
    "IPH": {"city": "Ipoh", "region": "Perak", "country": "Malasia"},
    "KUA": {"city": "Kuantan", "region": "Pahang", "country": "Malasia"},

    # =========================
    # INDONESIA (ID)
    # =========================
    "CGK": {"city": "Yakarta", "region": "Banten", "country": "Indonesia"},
    "HLP": {"city": "Yakarta", "region": "Yakarta", "country": "Indonesia"},
    "DPS": {"city": "Denpasar", "region": "Bali", "country": "Indonesia"},
    "SUB": {"city": "Surabaya", "region": "Java Oriental", "country": "Indonesia"},
    "UPG": {"city": "Makassar", "region": "Sulawesi Meridional", "country": "Indonesia"},
    "KNO": {"city": "Medan", "region": "Sumatra Septentrional", "country": "Indonesia"},
    "YIA": {"city": "Yogyakarta", "region": "Yogyakarta", "country": "Indonesia"},
    "JOG": {"city": "Yogyakarta", "region": "Yogyakarta", "country": "Indonesia"},
    "BDO": {"city": "Bandung", "region": "Java Occidental", "country": "Indonesia"},
    "SRG": {"city": "Semarang", "region": "Java Central", "country": "Indonesia"},
    "LOP": {"city": "Lombok", "region": "Nusa Tenggara Occidental", "country": "Indonesia"},
    "BPN": {"city": "Balikpapan", "region": "Kalimantan Oriental", "country": "Indonesia"},
    "MDC": {"city": "Manado", "region": "Sulawesi Septentrional", "country": "Indonesia"},
    "PKU": {"city": "Pekanbaru", "region": "Riau", "country": "Indonesia"},
    "PLM": {"city": "Palembang", "region": "Sumatra Meridional", "country": "Indonesia"},

    # =========================
    # FILIPINAS (PH)
    # =========================
    "MNL": {"city": "Manila", "region": "Gran Manila", "country": "Filipinas"},
    "CEB": {"city": "Cebú", "region": "Bisayas Centrales", "country": "Filipinas"},
    "CRK": {"city": "Clark/Angeles", "region": "Luzón Central", "country": "Filipinas"},
    "DVO": {"city": "Dávao", "region": "Dávao", "country": "Filipinas"},
    "ILO": {"city": "Iloílo", "region": "Bisayas Occidentales", "country": "Filipinas"},
    "PPS": {"city": "Puerto Princesa", "region": "Mimaropa", "country": "Filipinas"},
    "KLO": {"city": "Kalibo", "region": "Bisayas Occidentales", "country": "Filipinas"},
    "MPH": {"city": "Caticlan/Boracay", "region": "Bisayas Occidentales", "country": "Filipinas"},
    "BCD": {"city": "Bacolod", "region": "Bisayas Occidentales", "country": "Filipinas"},
    "ZAM": {"city": "Zamboanga", "region": "Zamboanga", "country": "Filipinas"},
    "GES": {"city": "General Santos", "region": "Soccsksargen", "country": "Filipinas"},
    "TAG": {"city": "Panglao/Bohol", "region": "Bisayas Centrales", "country": "Filipinas"},

    # =========================
    # VIETNAM (VN)
    # =========================
    "HAN": {"city": "Hanói", "region": "Hanói", "country": "Vietnam"},
    "SGN": {"city": "Ciudad Ho Chi Minh", "region": "Ciudad Ho Chi Minh", "country": "Vietnam"},
    "DAD": {"city": "Da Nang", "region": "Da Nang", "country": "Vietnam"},
    "CXR": {"city": "Nha Trang", "region": "Khánh Hòa", "country": "Vietnam"},
    "PQC": {"city": "Phú Quốc", "region": "Kiên Giang", "country": "Vietnam"},
    "DLI": {"city": "Da Lat", "region": "Lâm Đồng", "country": "Vietnam"},
    "HUI": {"city": "Huế", "region": "Thừa Thiên Huế", "country": "Vietnam"},
    "VCA": {"city": "Cần Thơ", "region": "Cần Thơ", "country": "Vietnam"},
    "VII": {"city": "Vinh", "region": "Nghệ An", "country": "Vietnam"},
    "HPH": {"city": "Hai Phong", "region": "Hai Phong", "country": "Vietnam"},

    # =========================
    # AUSTRALIA (AU)
    # =========================
    "SYD": {"city": "Sídney", "region": "Nueva Gales del Sur", "country": "Australia"},
    "MEL": {"city": "Melbourne", "region": "Victoria", "country": "Australia"},
    "BNE": {"city": "Brisbane", "region": "Queensland", "country": "Australia"},
    "PER": {"city": "Perth", "region": "Australia Occidental", "country": "Australia"},
    "ADL": {"city": "Adelaida", "region": "Australia Meridional", "country": "Australia"},
    "CBR": {"city": "Canberra", "region": "Territorio de la Capital Australiana", "country": "Australia"},
    "OOL": {"city": "Gold Coast", "region": "Queensland", "country": "Australia"},
    "CNS": {"city": "Cairns", "region": "Queensland", "country": "Australia"},
    "DRW": {"city": "Darwin", "region": "Territorio del Norte", "country": "Australia"},
    "HBA": {"city": "Hobart", "region": "Tasmania", "country": "Australia"},
    "TSV": {"city": "Townsville", "region": "Queensland", "country": "Australia"},
    "MCY": {"city": "Sunshine Coast", "region": "Queensland", "country": "Australia"},
    "AVV": {"city": "Avalon/Geelong", "region": "Victoria", "country": "Australia"},
    "LST": {"city": "Launceston", "region": "Tasmania", "country": "Australia"},
    "ASP": {"city": "Alice Springs", "region": "Territorio del Norte", "country": "Australia"},

    # =========================
    # NUEVA ZELANDA (NZ)
    # =========================
    "AKL": {"city": "Auckland", "region": "Auckland", "country": "Nueva Zelanda"},
    "WLG": {"city": "Wellington", "region": "Wellington", "country": "Nueva Zelanda"},
    "CHC": {"city": "Christchurch", "region": "Canterbury", "country": "Nueva Zelanda"},
    "ZQN": {"city": "Queenstown", "region": "Otago", "country": "Nueva Zelanda"},
    "DUD": {"city": "Dunedin", "region": "Otago", "country": "Nueva Zelanda"},
    "ROT": {"city": "Rotorua", "region": "Bay of Plenty", "country": "Nueva Zelanda"},
    "NPE": {"city": "Napier/Hastings", "region": "Hawke's Bay", "country": "Nueva Zelanda"},
    "NSN": {"city": "Nelson", "region": "Nelson", "country": "Nueva Zelanda"},
    "PMR": {"city": "Palmerston North", "region": "Manawatū-Whanganui", "country": "Nueva Zelanda"},
    "TRG": {"city": "Tauranga", "region": "Bay of Plenty", "country": "Nueva Zelanda"},
    "IVC": {"city": "Invercargill", "region": "Southland", "country": "Nueva Zelanda"},

    # =========================
    # SUDÁFRICA (ZA)
    # =========================
    "JNB": {"city": "Johannesburgo", "region": "Gauteng", "country": "Sudáfrica"},
    "CPT": {"city": "Ciudad del Cabo", "region": "Cabo Occidental", "country": "Sudáfrica"},
    "DUR": {"city": "Durban", "region": "KwaZulu-Natal", "country": "Sudáfrica"},
    "PLZ": {"city": "Port Elizabeth/Gqeberha", "region": "Cabo Oriental", "country": "Sudáfrica"},
    "ELS": {"city": "East London", "region": "Cabo Oriental", "country": "Sudáfrica"},
    "GRJ": {"city": "George", "region": "Cabo Occidental", "country": "Sudáfrica"},
    "BFN": {"city": "Bloemfontein", "region": "Estado Libre", "country": "Sudáfrica"},
    "HDS": {"city": "Hoedspruit", "region": "Limpopo", "country": "Sudáfrica"},
    "KIM": {"city": "Kimberley", "region": "Cabo Septentrional", "country": "Sudáfrica"},
    "MQP": {"city": "Nelspruit/Mbombela", "region": "Mpumalanga", "country": "Sudáfrica"},

    # =========================
    # EGIPTO (EG)
    # =========================
    "CAI": {"city": "El Cairo", "region": "El Cairo", "country": "Egipto"},
    "SPX": {"city": "Guiza", "region": "Guiza", "country": "Egipto"},
    "HRG": {"city": "Hurghada", "region": "Mar Rojo", "country": "Egipto"},
    "SSH": {"city": "Sharm el-Sheij", "region": "Sinaí del Sur", "country": "Egipto"},
    "LXR": {"city": "Luxor", "region": "Luxor", "country": "Egipto"},
    "ASW": {"city": "Asuán", "region": "Asuán", "country": "Egipto"},
    "HBE": {"city": "Alejandría", "region": "Alejandría", "country": "Egipto"},
    "RMF": {"city": "Marsa Alam", "region": "Mar Rojo", "country": "Egipto"},
    "ATZ": {"city": "Asyut", "region": "Asyut", "country": "Egipto"},
    "TCP": {"city": "Taba", "region": "Sinaí del Sur", "country": "Egipto"},

    # =========================
    # MARRUECOS (MA)
    # =========================
    "CMN": {"city": "Casablanca", "region": "Casablanca-Settat", "country": "Marruecos"},
    "RAK": {"city": "Marrakech", "region": "Marrakech-Safi", "country": "Marruecos"},
    "AGA": {"city": "Agadir", "region": "Souss-Massa", "country": "Marruecos"},
    "FEZ": {"city": "Fez", "region": "Fez-Mequinez", "country": "Marruecos"},
    "TNG": {"city": "Tánger", "region": "Tánger-Tetuán-Alhucemas", "country": "Marruecos"},
    "RBA": {"city": "Rabat", "region": "Rabat-Salé-Kenitra", "country": "Marruecos"},
    "OUD": {"city": "Oujda", "region": "Oriental", "country": "Marruecos"},
    "NDR": {"city": "Nador", "region": "Oriental", "country": "Marruecos"},
    "EUN": {"city": "El Aaiún", "region": "El Aaiún-Saguía el Hamra", "country": "Marruecos"},
    "ERH": {"city": "Errachidia", "region": "Draa-Tafilalet", "country": "Marruecos"},

    # =========================
    # EMIRATOS ÁRABES UNIDOS (AE)
    # =========================
    "DXB": {"city": "Dubái", "region": "Dubái", "country": "Emiratos Árabes Unidos"},
    "DWC": {"city": "Dubái", "region": "Dubái", "country": "Emiratos Árabes Unidos"},
    "AUH": {"city": "Abu Dabi", "region": "Abu Dabi", "country": "Emiratos Árabes Unidos"},
    "SHJ": {"city": "Sharjah", "region": "Sharjah", "country": "Emiratos Árabes Unidos"},
    "RKT": {"city": "Ras al-Jaima", "region": "Ras al-Jaima", "country": "Emiratos Árabes Unidos"},
    "AAN": {"city": "Al Ain", "region": "Abu Dabi", "country": "Emiratos Árabes Unidos"},
    "FJR": {"city": "Fujairah", "region": "Fujairah", "country": "Emiratos Árabes Unidos"},

}


def get_airport_metadata(iata_code):
    """Devuelve metadatos locales del aeropuerto por código IATA."""
    if not iata_code:
        return {}
    return AIRPORT_METADATA.get(str(iata_code).upper(), {})


def enrich_airport_data(airport):
    """Combina el diccionario recibido de la API con los metadatos locales."""
    iata_code = airport.get("iata_code") or airport.get("iata")
    metadata = get_airport_metadata(iata_code)

    airport_name = airport.get("name") or airport.get("airport_name") or iata_code or "Desconocido"

    return {
        **airport,
        "city": airport.get("city") or airport.get("city_name") or airport.get("municipality") or metadata.get("city") or airport_name,
        "region": airport.get("state") or airport.get("region") or airport.get("province") or metadata.get("region") or "Región no identificada",
        "country_name": airport.get("country_name") or metadata.get("country"),
    }
