COUNTRIES_ES = {
    "méxico": "MX",
    "mexico": "MX",
    "estados unidos": "US",
    "eeuu": "US",
    "eua": "US",
    "usa": "US",
    "canadá": "CA",
    "canada": "CA",
    "españa": "ES",
    "espana": "ES",
    "brasil": "BR",
    "argentina": "AR",
    "colombia": "CO",
    "chile": "CL",
    "perú": "PE",
    "peru": "PE",
    "francia": "FR",
    "alemania": "DE",
    "italia": "IT",
    "reino unido": "GB",
    "inglaterra": "GB",
    "gran bretaña": "GB",
    "gran bretana": "GB",
    "japón": "JP",
    "japon": "JP",

    # 30 países agregados
    "portugal": "PT",
    "países bajos": "NL",
    "paises bajos": "NL",
    "holanda": "NL",
    "bélgica": "BE",
    "belgica": "BE",
    "suiza": "CH",
    "austria": "AT",
    "irlanda": "IE",
    "noruega": "NO",
    "suecia": "SE",
    "dinamarca": "DK",
    "finlandia": "FI",
    "polonia": "PL",
    "república checa": "CZ",
    "republica checa": "CZ",
    "chequia": "CZ",
    "grecia": "GR",
    "turquía": "TR",
    "turquia": "TR",
    "rusia": "RU",
    "china": "CN",
    "india": "IN",
    "corea del sur": "KR",
    "corea": "KR",
    "tailandia": "TH",
    "singapur": "SG",
    "malasia": "MY",
    "indonesia": "ID",
    "filipinas": "PH",
    "vietnam": "VN",
    "australia": "AU",
    "nueva zelanda": "NZ",
    "sudáfrica": "ZA",
    "sudafrica": "ZA",
    "egipto": "EG",
    "marruecos": "MA",
    "emiratos árabes unidos": "AE",
    "emiratos arabes unidos": "AE",
    "emiratos": "AE",
}


def get_country_code(country_name):
    normalized = country_name.strip().lower()

    if normalized not in COUNTRIES_ES:
        return None

    return COUNTRIES_ES[normalized]
